[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
